### ISSUE TITLE
Nomi delle licenze coerenti con SPDX License List

### ISSUE THREAD

**Issue by pdavide** [teamdigitale/licenses#3]
Potrebbe essere utile conformare i nomi delle licenze allo standard definito da [SPDX License List](https://spdx.org/licenses/).
GitHub [si appoggia allo stesso standard](https://developer.github.com/v3/licenses/) per la gestione delle licenze dei repo e anche diversi strumenti per la gestione di pacchetti/dipendenze si avvalgono dello stesso standard (ad esempio [npm](https://docs.npmjs.com/files/package.json#license) o [composer](https://getcomposer.org/doc/04-schema.md#license)).

**Comment by alranel** [comment]
Mi sembra un ottimo suggerimento. Si tratta essenzialmente di modificare i nomi dei file di questo repository o vedi altri adattamenti da fare?

**Comment by pdavide** [comment]
Modificare i nomi e i riferimenti nel README, tutto qua.

**Comment by alranel** [comment]
Fatto nella PR #4

**Comment by ruphy** [comment]
grazie mille a entrambi: anche se in questo caso la licenza è usata in modo diverso, sicuramente gli standard sono apprezzati! Faccio il merge subito
